<!-- VANESSA ESMERALDA FLORES CERVANTES Matricula: ES172004305 -->
<!--CONEXION A LA BASE DE DATOS banca_carrousel-->

<?php

$conex = mysqli_connect("localhost","root","","criptomonedas"); 

?>

<!-- TENEMOS LA CONEXION DE LOCALHOST, USUARIO Y CONTRASENA EN ESTE CASO NO TENEMOS CONTRASENA POR LO CUAL LO DEJAMOS ABIERTO Y LA BASE DE DATOS DONDE SE REALIZARAN LAS CONSULTAS -->
